/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <total.h>
/* Header for class cn_beriru_jni_CallJniActivity */

#ifndef _Included_cn_beriru_jni_CallJniActivity
#define _Included_cn_beriru_jni_CallJniActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_beriru_jni_CallJniActivity
 * Method:    concat
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_beriru_jni_CallJniActivity_concat
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cn_beriru_jni_CallJniActivity
 * Method:    initDogProcess
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cn_beriru_jni_CallJniActivity_initWatchDog
  (JNIEnv *, jobject);



#ifdef __cplusplus
}
#endif
#endif
