/* DO NOT EDIT THIS FILE - it is machine generated */
#include "string"
#include <unistd.h>
#include <stdio.h>
#include <sys/inotify.h>
#include <poll.h>
#include <sys/wait.h>
#include <errno.h>
#include <fcntl.h>
#include <pthread.h>
#include <semaphore.h>
#include <android/log.h>


/* Header for class cn_beriru_jni_CallJniActivity */

#ifdef __cplusplus
extern "C" {
#endif

using namespace std;

const char* _s(JNIEnv* env, jstring str);

int init_watchdog();

void child_process(string monitor_dir);

void loge(const string& str);

void panic(const string& str);

#ifdef __cplusplus
}
#endif






